server:
  port: 8080
spring:
  cloud:
    stream:
      rabbit:
        default:
          producer:
            exchangeType: headers
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456